baseURL = 'https://mateus-bm.github.io/dev-resources-ghp'
languageCode = 'pt-BR'
title = 'Dev resources'
contentDir = 'content'
enableEmoji = true

defaultContentLanguage = 'pt-BR'
[languages]
  [languages.pt-BR]
    weight = 1

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
    subtitle = "Repositório de guias e documentos"
    [params.plausible]
        dataDomain = "mateus-bm.github.io"
        scriptURL  = "https://plausible.io/js/pa-4rh1jXgtWAhIQd25eSXVb.js"
    [params.docs]
        darkMode = true

[module]
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

[markup]
    [markup.tableOfContents]
      endLevel = 3
      startLevel = 1
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # https://jdhao.github.io/2019/12/29/hugo_html_not_shown/
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.image]
        useEmbedded = 'auto'
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true
