baseURL = 'https://mateus-bm.github.io/dev-resources-ghp/'
languageCode = 'pt-br'
title = 'Dev resources'
contentDir = 'content'
enableEmoji = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
    subtitle = "Repositório de guias e documentos"
    [params.docs]
    darkMode = true

[module]
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

[markup]
    [markup.tableOfContents]
      endLevel = 3
      startLevel = 1
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # https://jdhao.github.io/2019/12/29/hugo_html_not_shown/
  [markup.goldmark.parser]
    [markup.goldmark.parser.attribute]
      block = true